name: C Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt update && sudo apt install -y gcc

      - name: Compile C Code
        run: gcc -o CaesarCipher CaesarCipher.c

      - name: Run C Program
        run: ./CaesarCipher
        if: success()
