name: Build and Run C Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt update && sudo apt install -y gcc

      - name: Compile C Code
        run: gcc -o caesar caesar.c

      - name: Run C Program
        run: |
          echo "Running the Caesar Cipher Program"
          ./caesar
